# BIENVENU ! MODIFIER ICI LES PARAMETRES DE VOTRE PLATEFORME KATALOG
# --------------------------------------------------------------------------------------------------------------------------------------------------
#
# Konsilion - Licence juridique Creative Commons CC-BY-NC
# --------------------------------------------------------------------------------------------------------------------------------------------------



# NAVIGATION
# --------------------------------------------------------------------------------------------------------------------------------------------------

nav:

    - Accueil: pages/accueil.md
    
    - Recherche & D√©veloppement:
        
        - Projets: katalog/projets/home.md

        - T√¢ches: katalog/taches/home.md
        
        - √âvenements: katalog/taches/home.md

        - Ressources: katalog/ressources/home.md
        
        - Personnes: katalog/taches/home.md
        
    - Ing√©nierie collaborative:

        - De quoi parlons nous ?: pages/presentation.md

        - Katalog: pages/katalog.md

        - Konnect: pages/konnect.md   

    - √Ä propos: pages/informations.md
    
    - Contacts: pages/contacts.md



# SITE INFORMATIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

site_name: Konsilion - Low-technologie
site_author: Nicolas Br√©mond
site_description: D√©velopper, proposer et promouvoir la Low-technologie.


# repo_url: https://github.com/konsilion/katalog-template/
# edit_uri: edit/master/docs/

# LANGUE, COULEURS et LOGO
#
# [Liste des couleurs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)
# --------------------------------------------------------------------------------------------------------------------------------------------------

theme:
    language: fr
    palette:
        primary: green
        accent: blue
        scheme: default
    logo: https://konsilion.fr/wp/wp-content/uploads/2022/04/Logo_Konsilion_V2-1024x325.png
    favicon: https://konsilion.fr/wp/wp-content/uploads/2022/03/Logo_Konsilion_1.png
    name: material
    features:
      - navigation.indexes
      - navigation.tracking
      - navigation.top



extra:
  generator: false

# MENTIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

copyright: Une plateforme open-source cod√© avec ü§ç par <a href="#">Konsilion</a> - Licence juridique Creative Commons CC-BY-NC 4.0 <br> Un grand merci √† multi et mkdocs-material pour le support technique 







# AUTRES PARAMETRES - Ne pas modifier
# --------------------------------------------------------------------------------------------------------------------------------------------------
plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      
extra_css:
  - https://konsilion.github.io/katalog-setup/css/konsilion-datami.css
  - https://konsilion.github.io/katalog-setup/css/konsilion-mkdocs.css
  
extra_js:
  - https://kit.fontawesome.com/f9666d4f53.js
