# BIENVENU ! MODIFIER ICI LES PARAMETRES DE VOTRE PLATEFORME KATALOG
# --------------------------------------------------------------------------------------------------------------------------------------------------
#
# Konsilion - Licence juridique Creative Commons CC-BY-NC
# --------------------------------------------------------------------------------------------------------------------------------------------------

# NAVIGATION
# --------------------------------------------------------------------------------------------------------------------------------------------------

nav:

    - Accueil: index.md

    - Projets: etc/projets/home.md

    - Ressources: etc/ressources/home.md
    
    - Stockages: etc/stockages/home.md
    
    - Communauté: etc/communaute/home.md
    




# SITE INFORMATIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

site_name: Katalog - Plateforme de ressources ouvertes
site_author: Nicolas Brémond
site_description: Une plateforme de science ouverte et open-data, pour la Low-technologie.





# LANGUE, COULEURS et LOGO
# --------------------------------------------------------------------------------------------------------------------------------------------------

theme:
    language: fr
    palette:
        primary: green
        accent: orange
        scheme: default
    logo: https://konsilion.fr/wp/wp-content/uploads/2022/08/image-250x300.png
    favicon: https://konsilion.fr/wp/wp-content/uploads/2022/08/image-250x300.png
    name: material
    features:
      - navigation.indexes
      - navigation.tracking



# [Liste des couleurs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)





# MENTIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

copyright: Konsilion - Licence juridique Creative Commons CC-BY-NC 4.0




# CSS
# --------------------------------------------------------------------------------------------------------------------------------------------------

extra_css:
  - https://konsilion.github.io/katalog-setup/css/katalog.css
  - https://konsilion.github.io/katalog-setup/css/personnal-datami.css