# BIENVENU ! MODIFIER ICI LES PARAMETRES DE VOTRE PLATEFORME KATALOG
# --------------------------------------------------------------------------------------------------------------------------------------------------
#
# Konsilion - Licence juridique Creative Commons CC-BY-NC
# --------------------------------------------------------------------------------------------------------------------------------------------------



# NAVIGATION
# --------------------------------------------------------------------------------------------------------------------------------------------------

nav:

    - Accueil: index.md
    
    - Recherche & D√©veloppement:
    
        - Projets : katalog/projets/home.md

        - T√¢ches: katalog/taches/home.md
        
        - √âvenements: katalog/taches/home.md

        - Ressources: katalog/ressources/home.md
        
        - Personnes: katalog/ressources/home.md
        
        - üîç Moteur de recherche: katalog/search.md        

    - √Ä propos: katalog/who/home.md
    
    - Contacts: pages/contacts.md



# SITE INFORMATIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

site_name: Konsilion - Low-technologie
site_author: Nicolas Br√©mond
site_description: D√©velopper, proposer et promouvoir la Low-technologie.




# LANGUE, COULEURS et LOGO
#
# [Liste des couleurs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)
# --------------------------------------------------------------------------------------------------------------------------------------------------

theme:
    language: fr
    palette:
        primary: green
        accent: green
        scheme: default
    logo: https://konsilion.fr/wp/wp-content/uploads/2022/08/image-250x300.png
    favicon: https://konsilion.fr/wp/wp-content/uploads/2022/08/image-250x300.png
    name: material
    features:
      - navigation.indexes
      - navigation.tracking
      - navigation.top





# MENTIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

copyright: Konsilion - Licence juridique Creative Commons CC-BY-NC 4.0







# AUTRES PARAMETRES - Ne pas modifier
# --------------------------------------------------------------------------------------------------------------------------------------------------
plugins: []

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
